export default {
  ucapan: [
    "Doorrrrrr!",
    "Selamattt pagiii ayanggg",
    "Maaf kalau hari ini buat kecewa:(",
    "Maaf hari ini buat kamu mood turun",
    "Maaf buat hari ini jadi losestreak sampe 4hari 4malam",
    "Maaf aku ga jago dalam bermain game",
    "Maaf aku ga jago lindungin kamu",
    "Maaf aku ga jago dalam core, hyper atau support:(",
    "Maaf belum bisa jadi idaman kayak cowok/lovers lain",
    "Aku sadar by banyak kurangku selama ini",
    "Tapi aku berusaha melakukan yang bisa aku cobaaa",
    "Aku seneng kamu masih mau mabar sama aku ",
    "yang notabennya aku ini cupu by:(",
    "Maaf bikin point kamu turunnn banget, im sorry for that",
    "Semoga dengan aku bikin ini bisa ngebuat kamu sedikit lega",
    "Oh ya, maaf tadi terakhir langsung off, aku disitu nangis wkwk",
    "Aku nyadar diri dan mikir kenapa aku terlalu noob",
    "Aku langsung takut, takut bikin kamu kalah lagi",
    "Seenggaknya aku udah berusaha yang kucoba",
    "Gpp, kalau kamu marah, ngambek aku bisa terima kok, emang salah aku",
    "Tapi yang jelas, makasihhh udah sedia nemenin akuu mainn",
    "buah kedondong monyet berbulu",
    "I wuv chuuuu! UwU",
    "Aku bingung harus bilang apa lagiii",
    "Intinyaaa aku sayang kamuu biancaa, maaf buat bad day for youu:(",
    

  ],
  panggilan: ["Bianca ❣️"],
  colors: [
    "#F78DA7",
    "#FF6900",
    "#FCB900",
    "#7BDCB5",
    "#00D084",
    "#8ED1FC",
    "#0693E3",
    "#ABB8C3",
    "#EB144C",
    "#CC00FF",
    "#000000",
  ],
};
