export default {
  ucapan: [
    "Doorrrrrr!",
    "Hai kamu, Apa kabar?",
    "Kuharap kamu baik-baik aja ya disana",
    "meskipun aku tau kamu lagi pusing",
    "memikirkan segala hal yang saat ini kamu hadapi",
    "aku yakin, kamu pasti bisa melewatinya",
    "aku selalu support dari kejauhan meskipun kita tak sedekat dulu lagi",
    "kalau kamu lagi down, sedih, nangis, seneng",
    "tapi ga tau harus curhat ke siapa",
    "aku selalu siap untuk mendengarkanmu",
    "jadi tetap semangat ya!",
    "yay lebay ya? wkwkwk",
    "aku sedikit gabut, jadi bikin ini untuk kamu",
    "semoga suka sama orangnya ya hihihi *eh",
    "maksudnya suka sama web nya wkwkwk",
    "next nanti kutambahin beberapa fitur lagi",
    "kalau agak gabut ya hehe >.<",
    "buah kedondong monyet berbulu",
    "I wuv chuuuu! UwU",

  ],
  panggilan: ["Siti Annisa Azzahra ❣️"],
  colors: [
    "#F78DA7",
    "#FF6900",
    "#FCB900",
    "#7BDCB5",
    "#00D084",
    "#8ED1FC",
    "#0693E3",
    "#ABB8C3",
    "#EB144C",
    "#CC00FF",
    "#000000",
  ],
};
